### ISSUE TITLE
Unable to read "sw.lat" in the API

### ISSUE THREAD

**Issue by doriandevtech** [adrianhajdin/project_travel_advisor#14]
Here is the error that I got after following the tutorial until 1:03:45.

`TypeError: undefined is not an object (evaluating 'sw.lat')`

Can somebody help me please ?

**Comment by Pannu786** [comment]
Same here  I am stuck too. Did you able to find any solution?

**Comment by Pannu786** [comment]
Have you tried changing this code line on the App.js file?  
 `const [bounds, setBounds] = useState(null);  to  const [bounds, setBounds] = useState({ }); `

**Comment by doriandevtech** [comment]
Yeah I already tried it but thanks ! 🙂
Then I realised that my geolocation was not active... 😅
After having my geolocation turned on I replace `(null)` with `({ })` in App.js and now it seems to work (even though I still get many errors from the 'info' section on the browser's dev tools 😂)

**Comment by Pannu786** [comment]
Yea I gave up on this project and skipped the 2nd one too. Gonna do 3rd tomorrow.

**Comment by doriandevtech** [comment]
I managed to keep on going (pretty easily actually)... until my 500 API requests for this month were all used 😅
I just need to wait until march 1st to continue the project 😂

**Comment by Pannu786** [comment]
Glad it worked out for you. I might have had the same issue so I would retry to finish the Travel app after I successfully complete the Real Estate App.

**Comment by doriandevtech** [comment]
Alright ! Good luck for this new project, I might also try it later 😊

**Comment by doriandevtech** [comment]
Allowing my geolocation solved the issue ! 😊
