### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pannu786** [adrianhajdin/project_travel_advisor#15]
I am stuck @ [1:05:26](https://www.youtube.com/watch?v=GDa8kZLNhJ4&t=3926s)  ... 

I am getting this error
 <TypeError: Cannot read properties of undefined (reading 'lat')
    at getPlacesData (bundle.js:287:25)>

any help !!

**Comment by mrmahendra27** [comment]
> I am stuck @ [1:05:26](https://www.youtube.com/watch?v=GDa8kZLNhJ4&t=3926s) ...
> 
> I am getting this error <TypeError: Cannot read properties of undefined (reading 'lat') at getPlacesData (bundle.js:287:25)>
> 
> any help !!

did you get any solution, i am also stuck in this

**Comment by Pannu786** [comment]
> 
No, at that time I decided to move on to the next project. I am gonna try to do it again. However, someone on youtube commented this 

>  just put if(bounds != null) in getPlacesData(bounds.sw, bounds.ne) function 

so maybe try that.

**Comment by Pannu786** [comment]
It is somehow working now. IDK what I messed up last time but I tried to do it all from scratch and it is now working. If you get stuck and need help then let me know.
