### ISSUE TITLE
TypeError: Cannot read property 'ne' of null

### ISSUE THREAD

**Issue by csiki96** [adrianhajdin/project_travel_advisor#2]
Why I get this error, make no sense?

TypeError: Cannot read property 'ne' of null
(anonymous function)
src/App.js:23
  20 | }, [])
  21 | 
  22 | useEffect(() => {
> 23 |     console.log(bounds.ne)
     | ^  24 |     getPlacesData()
  25 |         .then((data) => {
  26 |             setPlaces(data);

**Comment by patriziomadferitmilione** [comment]
How did you solve this?
