### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'length')     at Map (Map.jsx:19:1)

### ISSUE THREAD

**Issue by Pablo-98** [adrianhajdin/project_travel_advisor#25]
I followed the tutorial but about a week after completing I cant seem to get the 'length' property to work with the GoogleMapReact component without getting this error back. Looking forward to feedback.

**Comment by ptrbui** [comment]
How were you able to solve this? 

I've been getting the "Cannot read properties of undefined (reading 'length')" error which I believe is the same error that was resolved here.
